export interface ILoginDataUserState {
  id:                   string;
  email:                string;
  first_name:           string;
  last_name:            string;
  gender:               string;
  address:              string;
  city:                 string;
  state:                string;
  country:              string;
  zip_code:             string;
  youtube_url:          string;
  about:                string;
  user_type:            string;
  birthdate:            string;
  fertile:              string;
  prejudice:            string;
  born_with_disability: string;
  preference_distance:  string;
  profession:           string;
  tokenNotification:    string;
  deviceType:           string;
  date_created:         string;
  lat:                  string;
  lon:                  string;
  interesthomo:         string;
  interestbi:           string;
  interesthetero:       string;
  sexualorientation:    string;
  genderborn:           string;
  tiic:                 string;
  interestsex:          string;
  interestfriend:       string;
  interestrelation:     string;
  status:               boolean;
  profile_image:        string;
}
export const LOGIN_USER_DATA_INITIAL_STATE:  ILoginDataUserState = {
  id:                   "",
  email:                "",
  first_name:           "",
  last_name:            "",
  gender:               "",
  address:              "",
  city:                 "",
  state:                "",
  country:              "",
  zip_code:             "",
  youtube_url:          "",
  about:                "",
  user_type:            "",
  birthdate:            "",
  fertile:              "",
  prejudice:            "",
  born_with_disability: "",
  preference_distance:  "",
  profession:           "",
  tokenNotification:    "",
  deviceType:           "",
  date_created:         "",
  lat:                  "",
  lon:                  "",
  interesthomo:         "",
  interestbi:           "",
  interesthetero:       "",
  sexualorientation:    "",
  genderborn:           "",
  tiic:                 "",
  interestsex:          "",
  interestfriend:       "",
  interestrelation:     "",
  status:               false,
  profile_image:        "",
}
